# Sam Kirkham 2019-11-22
### readTADA ###

# FUNCTION: reads TADA matlab output into a readable R object
# INPUT: quoted filepath to .mat file generated by TADA via the 'saveMAVIS' option
# OUTPUT: tibble, with a list for each signal type (cols = name, channel, signal, etc)
# requires R.matlab + dplyr packages (need to convert to df + then tibble for this to work)

readTADA <- function(matfile){
  require(R.matlab); require(dplyr)
  d <- readMat(matfile) %>% data.frame() %>% as_tibble # read .mat + convert to df/tibble
  for (i in 1:length(d)){colnames(d)[i] <- toString(d[[i]][1]$NAME)} # add colnames to tibble
  return(d) # return output
}
