#' Converts TADA matlab file to a nested tibble
#'
#' @description Reads .mat files produced by Task Dynamics Application
#' @param d quoted filepath to .mat file generated by TADA via the 'saveMAVIS' option
#' @return tibble with a list for each signal type

read_tada <- function(matfile){
  d <- R.matlab::readMat(matfile)
  d <- data.frame(d) # make df
  d <- tibble::as_tibble(d) # make tibble (handles nesting)
  for (i in 1:length(d)){colnames(d)[i] <- toString(d[[i]][1]$NAME)}
  return(d)
}